---
os: windows
language: shell
branches:
  only:
    - master
before_install:
  - choco install python --version 3.8.0
  - python -m pip install --upgrade pip
env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip install -r requirements.txt
script:
  - pyinstaller --onefile main.py
  - dist/main.exe
  - python test.py
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "dist/main.exe"
  skip_cleanup: true
  on:
    tags: true