---
os: windows
language: shell
branches:
  only:
    - master
before_install:
  - choco install python --version 3.8.0
  - python -m pip install --upgrade pip
env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip install -r requirements.txt
script:
  - pyinstaller --onefile main.py
  - dist/main.exe
  # - python test.py
before_deploy:
  - git config --local user.name "mochatek"
  - git config --local user.email "akashsabu@ymail.com"
  - COMMIT_MESSAGE=$(git log --format=%B -1)
  - VERSION=${COMMIT_MESSAGE##*:}
  - export TRAVIS_TAG=${VERSION}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "dist/main.exe"
  skip_cleanup: true